/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_transfer.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
file_transfer_0(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		FileName setfilename_0_arg;
		Content appendcontent_0_arg;
		int readcontent_0_arg;
		int closefile_0_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case setFileName:
		_xdr_argument = (xdrproc_t) xdr_FileName;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) setfilename_0_svc;
		break;

	case appendContent:
		_xdr_argument = (xdrproc_t) xdr_Content;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) appendcontent_0_svc;
		break;

	case readContent:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_Content;
		local = (char *(*)(char *, struct svc_req *)) readcontent_0_svc;
		break;

	case closeFile:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) closefile_0_svc;
		break;

	case listFile:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_FileList;
		local = (char *(*)(char *, struct svc_req *)) listfile_0_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FILE_TRANSFER, FILE_TRANSFER_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FILE_TRANSFER, FILE_TRANSFER_VER, file_transfer_0, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FILE_TRANSFER, FILE_TRANSFER_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FILE_TRANSFER, FILE_TRANSFER_VER, file_transfer_0, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FILE_TRANSFER, FILE_TRANSFER_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
