/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file_transfer.h"

int* setfilename_0_svc(char* argp, struct svc_req* rqstp)
{
    static int result;

    /*
     * insert server code here
     */

    return &result;
}

bool_t*
appendcontent_0_svc(Content* argp, struct svc_req* rqstp)
{
    static bool_t result;

    /*
     * insert server code here
     */

    return &result;
}

Content*
readcontent_0_svc(int* argp, struct svc_req* rqstp)
{
    static Content result;

    /*
     * insert server code here
     */

    return &result;
}

bool_t*
closefile_0_svc(int* argp, struct svc_req* rqstp)
{
    static bool_t result;

    /*
     * insert server code here
     */

    return &result;
}

char* listfile_0_svc(void* argp, struct svc_req* rqstp)
{
    static char result;

    /*
     * insert server code here
     */

    return &result;
}
