/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "file_transfer.h"

bool_t
xdr_Chunk (XDR *xdrs, Chunk objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 1000,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FileName (XDR *xdrs, FileName objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 255,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Content (XDR *xdrs, Content *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_Chunk (xdrs, objp->array))
		 return FALSE;
	return TRUE;
}
